# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2252e83f690124d3966e375e92b4684aeacdcd6b198e30c0d927b2ef0654032e15449ce72359355daab3768194f26f1b48eba1eaac6b76085a724df47579337d

test:
  secret_key_base: 2fb2fef9440592eed5cef4322b6f798f08072fbb89c0919d881a8a306878a3715073abc5200a7c68e856868bbea22e2f0467d340cad3650725fe0f99b2d9d947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
